//#region Criação de Tabelas

export const CriarTabelaAutor = `
    CREATE TABLE IF NOT EXISTS AUTOR (
        AUT_ID SERIAL PRIMARY KEY,
        AUT_NOME VARCHAR(150) NOT NULL,
        AUT_DATA_NASCIMENTO DATE,
        AUT_RESUMO TEXT,
        AUT_ATIVO BOOLEAN DEFAULT TRUE
    ); 
`
export const CriarTabelaLivro = `
    CREATE TABLE IF NOT EXISTS LIVRO (
      LIV_ID SERIAL PRIMARY KEY,
      LIV_TITULO VARCHAR(255) NOT NULL,
      LIV_AUT_ID INTEGER NOT NULL REFERENCES autor(AUT_ID),
      LIV_DATA_PUBLICACAO DATE,
      LIV_NUMERO_PAGINAS INTEGER,
      LIV_ISBN VARCHAR(14) UNIQUE,
      LIV_ATIVO BOOLEAN DEFAULT TRUE
    );
  `;

export const CriarTabelaCliente = `
    CREATE TABLE IF NOT EXISTS CLIENTE (
      CLI_ID SERIAL PRIMARY KEY,
      CLI_NOME VARCHAR(150) NOT NULL,
      CLI_EMAIL VARCHAR(255) UNIQUE NOT NULL,
      CLI_TELEFONE VARCHAR(20),
      CLI_DATA_NASCIMENTO DATE,
      CLI_ATIVO BOOLEAN DEFAULT TRUE
    );
  `;

  export const CriarTabelaEmprestimo = `
    CREATE TABLE IF NOT EXISTS EMPRESTIMO (
      EMP_ID SERIAL PRIMARY KEY,
      EMP_CLI_ID INTEGER NOT NULL REFERENCES CLIENTE(CLI_ID),
      EMP_LIV_ID INTEGER NOT NULL REFERENCES LIVRO(LIV_ID),
      EMP_DATA_EMPRESTIMO DATE NOT NULL,
      EMP_DATA_DEVOLUCAO DATE
    );
  `;
  
//#endregion