// #region Criação de Tabelas

export const CriarTabelaAutor = `
    CREATE TABLE IF NOT EXISTS AUTOR (
        AUT_ID SERIAL PRIMARY KEY,
        AUT_NOME VARCHAR(150) NOT NULL,
        AUT_DATA_NASCIMENTO DATE,
        AUT_RESUMO TEXT,
        AUT_ATIVO BOOLEAN DEFAULT TRUE
    ); 
`
export const CriarTabelaLivro = `
    CREATE TABLE IF NOT EXISTS LIVRO (
      LIV_ID SERIAL PRIMARY KEY,
      LIV_TITULO VARCHAR(255) NOT NULL,
      LIV_AUT_ID INTEGER NOT NULL REFERENCES autor(AUT_ID),
      LIV_DATA_PUBLICACAO DATE,
      LIV_NUMERO_PAGINAS INTEGER,
      LIV_ISBN VARCHAR(14) UNIQUE,
      LIV_QUANTIDADE_DISPONIVEL INT,
      LIV_ATIVO BOOLEAN DEFAULT TRUE
    );
  `;

export const CriarTabelaCliente = `
    CREATE TABLE IF NOT EXISTS CLIENTE (
      CLI_ID SERIAL PRIMARY KEY,
      CLI_NOME VARCHAR(150) NOT NULL,
      CLI_EMAIL VARCHAR(255) UNIQUE NOT NULL,
      CLI_TELEFONE VARCHAR(20),
      CLI_DATA_NASCIMENTO DATE,
      CLI_ATIVO BOOLEAN DEFAULT TRUE
    );
  `;

  export const CriarTabelaEmprestimo = `
    CREATE TABLE IF NOT EXISTS EMPRESTIMO (
      EMP_ID SERIAL PRIMARY KEY,
      EMP_CLI_ID INTEGER NOT NULL REFERENCES CLIENTE(CLI_ID),
      EMP_LIV_ID INTEGER NOT NULL REFERENCES LIVRO(LIV_ID),
      EMP_DATA_EMPRESTIMO DATE NOT NULL,
      EMP_DATA_DEVOLUCAO DATE,
      EMP_QUANTIDADE INT
    );
  `;
  
// #endregion

// #region Inserts

export const InserirAutor = `
    INSERT INTO AUTOR (AUT_NOME, AUT_DATA_NASCIMENTO, AUT_RESUMO, AUT_ATIVO)
    VALUES ($1, $2, $3, $4)
`;

export const InserirLivro = `
    INSERT INTO LIVRO (LIV_TITULO, LIV_AUT_ID, LIV_DATA_PUBLICACAO, LIV_NUMERO_PAGINAS, LIV_ISBN, LIV_QUANTIDADE_DISPONIVEL, LIV_ATIVO)
    VALUES ($1, $2, $3, $4, $5, $6, $7)
`;

export const InserirCliente = `
  INSERT INTO CLIENTE (CLI_NOME, CLI_EMAIL, CLI_TELEFONE, CLI_DATA_NASCIMENTO, CLI_ATIVO)
  VALUES ($1, $2, $3, $4, $5)
`

export const InserirEmprestimo = `
  INSERT INTO EMPRESTIMO (EMP_CLI_ID, EMP_LIV_ID, EMP_DATA_EMPRESTIMO, EMP_DATA_DEVOLUCAO, EMP_QUANTIDADE)
  VALUES ($1, $2, $3, $4, $5)
`

//#endregion

// #region Selects

export const ListarAutores = `
    SELECT 
      AUT.AUT_ID AS ID, 
      AUT.AUT_NOME AS NOME, 
      TO_CHAR(AUT_DATA_NASCIMENTO,'DD/MM/YYYY') AS DATA_NASCIMENTO, 
      AUT.AUT_RESUMO AS RESUMO,
      AUT.AUT_ATIVO AS ATIVO
    FROM AUTOR AUT
    ORDER BY AUT.AUT_NOME;
`;

export const ListarAutorPorId = `
    SELECT
      AUT.AUT_ID AS ID, 
      AUT.AUT_NOME AS NOME, 
      TO_CHAR(AUT_DATA_NASCIMENTO,'DD/MM/YYYY') AS DATA_NASCIMENTO, 
      AUT.AUT_RESUMO AS RESUMO,
      AUT.AUT_ATIVO AS ATIVO
    FROM AUTOR AUT
    WHERE AUT.AUT_ID = $1;
`;

export const ListarLivros = `
    SELECT
      LIV.LIV_ID AS ID,
      LIV.LIV_TITULO AS TITULO,
      AUT.AUT_ID AS ID_AUTOR,
      AUT.AUT_NOME AS NOME_AUTOR,
      TO_CHAR(LIV.LIV_DATA_PUBLICACAO,'DD/MM/YYYY') AS DATA_PUBLICACAO,
      LIV.LIV_NUMERO_PAGINAS AS NUMERO_PAGINAS,
      LIV.LIV_ISBN AS ISBN,
      LIV.LIV_QUANTIDADE_DISPONIVEL AS QUANTIDADE_DISPONIVEL,
      LIV.LIV_ATIVO AS ATIVO
    FROM LIVRO LIV
    INNER JOIN AUTOR AUT ON LIV.LIV_AUT_ID = AUT.AUT_ID
    ORDER BY LIV.LIV_TITULO;
`;

export const ListarLivroPorId = `
    SELECT
      LIV.LIV_ID AS ID,
      LIV.LIV_TITULO AS TITULO,
      AUT.AUT_ID AS ID_AUTOR,
      AUT.AUT_NOME AS NOME_AUTOR,
      TO_CHAR(LIV.LIV_DATA_PUBLICACAO,'DD/MM/YYYY') AS DATA_PUBLICACAO,
      LIV.LIV_NUMERO_PAGINAS AS NUMERO_PAGINAS,
      LIV.LIV_ISBN AS ISBN,
      LIV.LIV_QUANTIDADE_DISPONIVEL AS QUANTIDADE_DISPONIVEL,
      LIV.LIV_ATIVO AS ATIVO
    FROM LIVRO LIV
    INNER JOIN AUTOR AUT ON LIV.LIV_AUT_ID = AUT.AUT_ID
    WHERE LIV.LIV_ID = $1;
`;

export const ListarClientes = `
  SELECT
    CLI.CLI_ID AS ID,
    CLI.CLI_Nome AS NOME,
    CLI.CLI_Email AS EMAIL,
    CLI.CLI_Telefone AS TELEFONE,
    TO_CHAR(CLI.CLI_DATA_NASCIMENTO,'DD/MM/YYYY') AS DATA_NASCIMENTO,
    CLI.CLI_ATIVO AS ATIVO
  FROM CLIENTE CLI
  ORDER BY CLI.CLI_Nome;
`

export const ListarClientesPorId = `
  SELECT
    CLI.CLI_ID AS ID,
    CLI.CLI_Nome AS NOME,
    CLI.CLI_Email AS EMAIL,
    CLI.CLI_Telefone AS TELEFONE,
    TO_CHAR(CLI.CLI_DATA_NASCIMENTO,'DD/MM/YYYY') AS DATA_NASCIMENTO,
    CLI.CLI_ATIVO AS ATIVO
  FROM CLIENTE CLI
  WHERE CLI.CLI_ID = $1
  ORDER BY CLI.CLI_Nome;
`

export const ListarEmprestimos = `
  SELECT
    EMP.EMP_ID AS ID,
    CLI.CLI_ID AS ID_CLIENTE,
    CLI.CLI_NOME AS NOME_CLIENTE,
    LIV.LIV_ID AS ID_LIVRO,
    LIV.LIV_TITULO AS NOME_LIVRO,
    TO_CHAR(EMP.EMP_DATA_EMPRESTIMO, 'DD/MM/YYYY') AS DATA_EMPRESTIMO,
    TO_CHAR(EMP.EMP_DATA_DEVOLUCAO, 'DD/MM/YYYY') AS DATA_DEVOLUCAO,
    EMP.EMP_QUANTIDADE AS QUANTIDADE
  FROM EMPRESTIMO EMP
  INNER JOIN CLIENTE CLI ON CLI.CLI_ID = EMP_CLI_ID
  INNER JOIN LIVRO LIV ON LIV.LIV_ID = EMP_LIV_ID
`

export const ListarEmprestimosPorId = `
  SELECT
    EMP.EMP_ID AS ID,
    CLI.CLI_ID AS ID_CLIENTE,
    CLI.CLI_NOME AS NOME_CLIENTE,
    LIV.LIV_ID AS ID_LIVRO,
    LIV.LIV_TITULO AS NOME_LIVRO,
    TO_CHAR(EMP.EMP_DATA_EMPRESTIMO, 'DD/MM/YYYY') AS DATA_EMPRESTIMO,
    TO_CHAR(EMP.EMP_DATA_DEVOLUCAO, 'DD/MM/YYYY') AS DATA_DEVOLUCAO,
    EMP.EMP_QUANTIDADE AS QUANTIDADE
  FROM EMPRESTIMO EMP
  INNER JOIN CLIENTE CLI ON CLI.CLI_ID = EMP_CLI_ID
  INNER JOIN LIVRO LIV ON LIV.LIV_ID = EMP_LIV_ID
  WHERE EMP.EMP_ID = $1;
`

// #endregion

// #region Updates

export const AtualizarAutor = `
    UPDATE AUTOR
    SET AUT_NOME = $1, AUT_DATA_NASCIMENTO = $2, AUT_RESUMO = $3, AUT_ATIVO = $4
    WHERE AUT_ID = $5;
`;

export const AtualizarLivro = `
    UPDATE LIVRO
    SET LIV_TITULO = $1, LIV_AUT_ID = $2, LIV_DATA_PUBLICACAO = $3, LIV_NUMERO_PAGINAS = $4, LIV_ISBN = $5, LIV_QUANTIDADE_DISPONIVEL = $6, LIV_ATIVO = $7
    WHERE LIV_ID = $8;
`;

export const AtualizaQuantidadeLivroEmprestimo = `
  UPDATE LIVRO
  SET LIV_QUANTIDADE_DISPONIVEL = LIV_QUANTIDADE_DISPONIVEL - $1
  WHERE LIV_ID = $2
`;

export const AtualizaQuantidadeLivroDevolucao = `
  UPDATE LIVRO
  SET LIV_QUANTIDADE_DISPONIVEL = LIV_QUANTIDADE_DISPONIVEL + $1
  WHERE LIV_ID = $2
`;

export const AtualizarCliente = `
  UPDATE CLIENTE
  SET CLI_NOME = $1, CLI_EMAIL = $2, CLI_TELEFONE = $3, CLI_DATA_NASCIMENTO = $4, CLI_ATIVO = $5
  WHERE CLI_ID = $6;
`

export const RegistrarDevolucao = `
  UPDATE EMPRESTIMO
  SET EMP_DATA_DEVOLUCAO = $1
  WHERE EMP_ID = $2
`

// #endregion

// #region Deletes

export const RemoverAutor = `
    DELETE FROM AUTOR
    WHERE AUT_ID = $1;
`;

export const RemoverLivro = `
    DELETE FROM LIVRO
    WHERE LIV_ID = $1;
`;

export const RemoverCliente = `
  DELETE FROM CLIENTE
  WHERE CLI_ID = $1;
`

// #endregion